#!/usr/bin/env python
# Copyright 2014-2021 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Timothy Berkelbach <tim.berkelbach@gmail.com>
#         James McClain <jdmcclain47@gmail.com>
#         Hong-Zhou Ye <hzyechem@gmail.com>
#


'''
kpoint-adapted and spin-adapted MP2
t2[i,j,a,b] = <ij|ab> / D_ij^ab
'''

''' To-do
[ ] optimize nocc-blksize n kernel_s2_incore
'''

import numpy as np
from scipy.linalg import block_diag
import tempfile
import h5py

from pyscf import lib
from pyscf.lib import logger, einsum
from pyscf.mp import mp2
from pyscf.pbc import df
from pyscf.pbc.lib import kpts_helper
from pyscf.lib.parameters import LARGE_DENOM
from pyscf import __config__

WITH_T2 = getattr(__config__, 'mp_mp2_with_t2', True)

def kernel(mp, mo_energy=None, mo_coeff=None, eris=None, with_t2=WITH_T2, verbose=None):
    """Computes k-point RMP2 energy.

    Args:
        mp (KMP2): an instance of KMP2
        mo_energy (list): a list of np.ndarray. Each array contains MO energies of
                          shape (Nmo,) for one kpt
        mo_coeff (list): a list of np.ndarray. Each array contains MO coefficients
                         of shape (Nao, Nmo) for one kpt
        eris: generated by mp.ao2mo()
        verbose (int, optional): level of verbosity. Defaults to logger.NOTE (=3).
        with_t2 (bool, optional): whether to compute t2 amplitudes. Defaults to WITH_T2 (=True).

    Returns:
        KMP2 energy and t2 amplitudes (=None if with_t2 is False)
    """
    cput0 = (logger.process_clock(), logger.perf_counter())
    log = logger.new_logger(mp, verbose)

    nmo = mp.nmo
    nocc = mp.nocc
    nvir = nmo - nocc
    nkpts = mp.nkpts
    with_df_ints = mp.with_df_ints

    mp._memory_sanity_check(with_t2)

    if with_t2:
        t2 = np.zeros((nkpts, nkpts, nkpts, nocc, nocc, nvir, nvir), dtype=complex)
    else:
        t2 = None

    if eris is None: eris = mp.ao2mo(mo_coeff=mo_coeff)

    kconserv = mp.khelper.kconserv

    if mo_energy is None: mo_energy = eris.mo_energy
    mo_e_o = [mo_energy[k][:nocc] for k in range(nkpts)]
    mo_e_v = [mo_energy[k][nocc:] for k in range(nkpts)]

    # Get location of non-zero/padded elements in occupied and virtual space
    nonzero_opadding, nonzero_vpadding = padding_k_idx(mp, kind="split")

    # helper functions
    def get_eia(ki,ka):
        # Remove zero/padded elements from denominator
        eia = LARGE_DENOM * np.ones((nocc, nvir), dtype=mo_energy[0].dtype)
        n0_ovp_ia = np.ix_(nonzero_opadding[ki], nonzero_vpadding[ka])
        eia[n0_ovp_ia] = (mo_e_o[ki][:,None] - mo_e_v[ka])[n0_ovp_ia]
        return eia
    def _contract1(kijab, shls_slice, eia, ejb, gdi, gxi=None):
        r''' The energy for the (ka,kb)-pair is (ignoring denominator)
        e = 2*|(ia|jb)|^2 + 2*|(jb|ia)|^2 - ( (ia|jb)^*(ib|ja) + c.c. )
          = 2*( |(ia|jb)|^2 + |(jb|ia)|^2 - Re{ (ia|jb)^*(ib|ja) } )
        Using the second line saves one einsum.
        '''
        p0,p1 = shls_slice
        ejab = lib.direct_sum('ia+jb->ijab', eia[p0:p1], ejb)
        t2i = gdi.conj() / ejab
        ed_this = einsum('ijab,ijab->', t2i, gdi) * 2.
        if with_t2:
            t2[kijab[0],kijab[1],kijab[2],p0:p1] = t2i
        if gxi is None:
            ex_this = -einsum('ijab,ijba->', t2i, gdi)
        else:
            ex_this = -einsum('ijab,ijba->', t2i, gxi) * 2 # (ka,kb) swap
            t2i = None
            t2i = gxi.conj() / ejab.transpose(0,1,3,2)
            ed_this += einsum('ijab,ijab->', t2i, gxi) * 2.
            if with_t2:
                t2[kijab[0],kijab[1],kijab[3],p0:p1] = t2i
        t2i = ejab = None
        return ed_this.real, ex_this.real

    # compute
    mem_avail = mp.max_memory - lib.current_memory()[0]
    # 4 ovv-type tensors: gdi, gxi, ejab, t2i
    blksize = int(np.floor(mem_avail*0.7 / (nocc*nvir**2.*4 * 16/1e6)))
    cache_eris = not (mp.with_df_ints or mp.less_mem)
    cput1 = (logger.process_clock(), logger.perf_counter())
    emp2_ss = emp2_os = 0.
    for ki in range(nkpts):
        for kj in range(nkpts):
            kblist = [kconserv[ki,ka,kj] for ka in range(nkpts)]
            done = {(ka,kblist[ka]):False for ka in range(nkpts)}
            for ka in range(nkpts):
                kb = kblist[ka]
                if done[(ka,kb)] and done[(kb,ka)]:
                    continue

                kijab = (ki,kj,ka,kb)
                eia = get_eia(ki,ka)
                ejb = get_eia(kj,kb)

                p1 = 0
                for gdi,gxi in eris.loop_oovv(kijab, blksize=blksize,
                                              cache_eris=cache_eris):
                    p0 = p1
                    p1 = p0 + gdi.shape[0]

                    edi, exi = _contract1(kijab, (p0,p1), eia, ejb, gdi, gxi)

                    emp2_ss += edi*0.5 + exi
                    emp2_os += edi*0.5
                    gdi = gxi = None

                done[(ka,kb)] = done[(kb,ka)] = True

            cput1 = log.timer_debug1('(ki,kj) = (%d,%d)'%(ki,kj), *cput1)

    log.timer(mp.__class__.__name__, *cput0)

    emp2_ss /= nkpts
    emp2_os /= nkpts
    emp2 = emp2_ss + emp2_os

    return emp2, t2, emp2_ss, emp2_os

def kernel_s2(mp, mo_energy=None, mo_coeff=None, eris=None, with_t2=WITH_T2, verbose=None):
    """Computes k-point RMP2 energy.

    Args:
        mp (KMP2): an instance of KMP2
        mo_energy (list): a list of np.ndarray. Each array contains MO energies of
                          shape (Nmo,) for one kpt
        mo_coeff (list): a list of np.ndarray. Each array contains MO coefficients
                         of shape (Nao, Nmo) for one kpt
        eris: generated by mp.ao2mo()
        verbose (int, optional): level of verbosity. Defaults to logger.NOTE (=3).
        with_t2 (bool, optional): whether to compute t2 amplitudes. Defaults to WITH_T2 (=True).

    Returns:
        KMP2 energy and t2 amplitudes (=None if with_t2 is False)
    """
    cput0 = (logger.process_clock(), logger.perf_counter())
    log = logger.new_logger(mp, verbose)

    nmo = mp.nmo
    nocc = mp.nocc
    nvir = nmo - nocc
    nkpts = mp.nkpts
    with_df_ints = mp.with_df_ints

    mp._memory_sanity_check(with_t2)

    if with_t2:
        t2 = np.zeros((nkpts, nkpts, nkpts, nocc, nocc, nvir, nvir), dtype=complex)
    else:
        t2 = None

    if eris is None: eris = mp.ao2mo(mo_coeff=mo_coeff)

    kconserv = mp.khelper.kconserv

    if mo_energy is None: mo_energy = eris.mo_energy
    mo_e_o = [mo_energy[k][:nocc] for k in range(nkpts)]
    mo_e_v = [mo_energy[k][nocc:] for k in range(nkpts)]

    # Get location of non-zero/padded elements in occupied and virtual space
    nonzero_opadding, nonzero_vpadding = padding_k_idx(mp, kind="split")

    # helper functions
    def get_eia(ki,ka):
        # Remove zero/padded elements from denominator
        eia = LARGE_DENOM * np.ones((nocc, nvir), dtype=mo_energy[0].dtype)
        n0_ovp_ia = np.ix_(nonzero_opadding[ki], nonzero_vpadding[ka])
        eia[n0_ovp_ia] = (mo_e_o[ki][:,None] - mo_e_v[ka])[n0_ovp_ia]
        return eia
    def _contract1(kijab, shls_slice, eia, ejb, gdi, gxi=None):
        r''' The energy for the (ka,kb)-pair is (ignoring denominator)
        e = 2*|(ia|jb)|^2 + 2*|(jb|ia)|^2 - ( (ia|jb)^*(ib|ja) + c.c. )
          = 2*( |(ia|jb)|^2 + |(jb|ia)|^2 - Re{ (ia|jb)^*(ib|ja) } )
        Using the second line saves one einsum.
        '''
        p0,p1 = shls_slice
        ejab = lib.direct_sum('ia+jb->ijab', eia[p0:p1], ejb)
        t2i = gdi.conj() / ejab
        ed_this = einsum('ijab,ijab->', t2i, gdi) * 2.
        if with_t2:
            t2[kijab[0],kijab[1],kijab[2],p0:p1] = t2i
        if gxi is None:
            ex_this = -einsum('ijab,ijba->', t2i, gdi)
        else:
            ex_this = -einsum('ijab,ijba->', t2i, gxi) # (ka,kb) swap
        t2i = ejab = None
        return ed_this.real, ex_this.real

    # compute
    mem_avail = mp.max_memory - lib.current_memory()[0]
    # 4 ovv-type tensors: gdi, gxi, ejab, t2i
    blksize = int(np.floor(mem_avail*0.7 / (nocc*nvir**2.*4 * 16/1e6)))
    cache_eris = not (mp.with_df_ints or mp.less_mem)
    cput1 = (logger.process_clock(), logger.perf_counter())
    emp2_ss = emp2_os = 0.
    kilist = range(nkpts) if mp.kilist is None else mp.kilist
    for ki in kilist:
        for ka in range(nkpts):
            kia = ki*nkpts + ka
            for kj in range(nkpts):
                kb = kconserv[ki,ka,kj]
                kjb = kj*nkpts + kb
                if kia < kjb:
                    continue
                fac = 1 if kia == kjb else 2

                kijab = (ki,kj,ka,kb)
                eia = get_eia(ki,ka)
                ejb = get_eia(kj,kb)

                p1 = 0
                for gdi,gxi in eris.loop_oovv(kijab, blksize=blksize,
                                              cache_eris=cache_eris):
                    p0 = p1
                    p1 = p0 + gdi.shape[0]

                    edi, exi = _contract1(kijab, (p0,p1), eia, ejb, gdi, gxi)
                    edi *= fac
                    exi *= fac

                    emp2_ss += edi*0.5 + exi
                    emp2_os += edi*0.5
                    gdi = gxi = None

            cput1 = log.timer_debug1('(ki,ka) = (%d,%d)'%(ki,ka), *cput1)
            log.debug2('So far E_corr = %.15g (SS)  %.15g (OS)  %.15g',
                       emp2_ss/nkpts, emp2_os/nkpts, (emp2_ss+emp2_os)/nkpts)

    log.timer(mp.__class__.__name__, *cput0)

    emp2_ss /= nkpts
    emp2_os /= nkpts
    emp2 = emp2_ss + emp2_os

    return emp2, t2, emp2_ss, emp2_os

def kernel_s2_incore(mp, mo_energy=None, mo_coeff=None, eris=None, with_t2=WITH_T2,
                     verbose=None):
    """Computes k-point RMP2 energy.

    Args:
        mp (KMP2): an instance of KMP2
        mo_energy (list): a list of np.ndarray. Each array contains MO energies of
                          shape (Nmo,) for one kpt
        mo_coeff (list): a list of np.ndarray. Each array contains MO coefficients
                         of shape (Nao, Nmo) for one kpt
        eris: generated by mp.ao2mo()
        verbose (int, optional): level of verbosity. Defaults to logger.NOTE (=3).
        with_t2 (bool, optional): whether to compute t2 amplitudes. Defaults to WITH_T2 (=True).

    Returns:
        KMP2 energy and t2 amplitudes (=None if with_t2 is False)
    """
    cput0 = (logger.process_clock(), logger.perf_counter())
    log = logger.new_logger(mp, verbose)

    nmo = mp.nmo
    nocc = mp.nocc
    nvir = nmo - nocc
    nkpts = mp.nkpts
    with_df_ints = mp.with_df_ints
    if not with_df_ints:
        log.error('kernel_s2_incore must use RSDF')
        raise RuntimeError
    naux = mp._scf.with_df.auxcell.nao_nr()

    mp._memory_sanity_check(with_t2)

    if with_t2:
        log.error('kernel_s2_incore does not support caching t2 for now.')
        raise NotImplementedError
        t2 = np.zeros((nkpts, nkpts, nkpts, nocc, nocc, nvir, nvir), dtype=complex)
    else:
        t2 = None

    if eris is None: eris = mp.ao2mo_incore(mo_coeff=mo_coeff)

    kconserv = mp.khelper.kconserv

    if mo_energy is None: mo_energy = eris.mo_energy
    mo_e_o = [mo_energy[k][:nocc] for k in range(nkpts)]
    mo_e_v = [mo_energy[k][nocc:] for k in range(nkpts)]

    # Get location of non-zero/padded elements in occupied and virtual space
    nonzero_opadding, nonzero_vpadding = padding_k_idx(mp, kind="split")

    # helper functions
    def get_eia(ki,ka,oslice=None):
        if oslice is None: oslice = (0,nocc)
        i0,i1 = oslice
        di = i1 - i0
        # Remove zero/padded elements from denominator
        eia = LARGE_DENOM * np.ones((nocc, nvir), dtype=mo_energy[0].dtype)
        n0_ovp_ia = np.ix_(nonzero_opadding[ki], nonzero_vpadding[ka])
        eia[n0_ovp_ia] = (mo_e_o[ki][:,None] - mo_e_v[ka])[n0_ovp_ia]
        eia = eia[i0:i1]
        return eia
    def _contract1(kijab, shls_slice, eia, ejb, gdi, gxi=None):
        r''' The energy for the (ka,kb)-pair is (ignoring denominator)
        e = 2*|(ia|jb)|^2 + 2*|(jb|ia)|^2 - ( (ia|jb)^*(ib|ja) + c.c. )
          = 2*( |(ia|jb)|^2 + |(jb|ia)|^2 - Re{ (ia|jb)^*(ib|ja) } )
        Using the second line saves one einsum.
        '''
        p0,p1 = shls_slice
        ejab = lib.direct_sum('ia+jb->ijab', eia[p0:p1], ejb)
        t2i = gdi.conj() / ejab
        ed_this = einsum('ijab,ijab->', t2i, gdi) * 2.
        if with_t2:
            # [TODO] fix p index (shifting by i0?)
            t2[kijab[0],kijab[1],kijab[2],p0:p1] = t2i
        if gxi is None:
            ex_this = -einsum('ijab,ijba->', t2i, gdi)
        else:
            ex_this = -einsum('ijab,ijba->', t2i, gxi) # (ka,kb) swap
        t2i = ejab = None
        return ed_this.real, ex_this.real

    # compute
    mem_avail = mp.max_memory - lib.current_memory()[0]
    # Using 60% of mem to cache Lov
    noccblksize = min(nocc, max(1,int(np.floor(mem_avail*0.6/
                                               (2*naux*nvir*nkpts**2*16/1e6)))))
    if noccblksize >= nocc*0.5: noccblksize = nocc
    occslices = [(i0,i1) for i0,i1 in lib.prange(0,nocc,noccblksize)]
    noccblk = len(occslices)
    log.info('noccblksize= %d  noccblk= %d', noccblksize, noccblk)
    log.debug('occslices= %s', occslices)
    # ovv-type intermidiate tensors: gdi, gxi, ejab, t2i
    blksize = int(np.floor(mem_avail*0.3 / (noccblksize*nvir**2.*4 * 16/1e6)))
    cache_eris = not (mp.with_df_ints or mp.less_mem)
    kilist = range(nkpts) if mp.kilist is None else mp.kilist

    def _get_di(eris, cderi):
        if eris.j3c_order == 'Lij':
            return cderi[0,0].shape[1]
        else:
            return cderi[0,0].shape[0]
    def _get_oovv(eris, L1, L2, shls_slice_i=None):
        if eris.j3c_order == 'Lij':
            scntr = 'Lia,Ljb->iajb'
            l1 = L1 if shls_slice_i is None else L1[:,shls_slice_i[0]:shls_slice_i[1]]
        else:
            scntr = 'iaL,jbL->iajb'
            l1 = L1 if shls_slice_i is None else L1[shls_slice_i[0]:shls_slice_i[1]]
        return einsum(scntr, l1, L2).transpose(0,2,1,3) / nkpts
    def _contract1occ(eris, cderi, oslice, cderi2=None, oslice2=None):
        cput1 = (logger.process_clock(), logger.perf_counter())

        if cderi2 is None:
            cderi2 = cderi
            oslice2 = oslice
        di = _get_di(eris, cderi)

        ess = eos = 0
        for ki in kilist:
            for ka in range(nkpts):
                kia = ki*nkpts + ka
                for kj in range(nkpts):
                    kb = kconserv[ki,ka,kj]
                    kjb = kj*nkpts + kb
                    if kia < kjb:
                        continue
                    fac = 1 if kia == kjb else 2

                    kijab = (ki,kj,ka,kb)
                    swap_kakb = ka != kb
                    eia = get_eia(ki,ka,oslice)
                    ejb = get_eia(kj,kb,oslice2)

                    for p0,p1 in lib.prange(0, di, blksize):

                        gdi = _get_oovv(eris, cderi[ki,ka], cderi2[kj,kb], (p0,p1))
                        if swap_kakb:
                            gxi = _get_oovv(eris, cderi[ki,kb], cderi2[kj,ka], (p0,p1))
                        else:
                            gxi = None
                        edi, exi = _contract1(kijab, (p0,p1), eia, ejb, gdi, gxi)
                        edi *= fac
                        exi *= fac

                        ess += edi*0.5 + exi
                        eos += edi*0.5
                        gdi = gxi = None

                if log.verbose >= logger.DEBUG2:
                    cput1 = log.timer('(ki,ka) = (%d,%d)'%(ki,ka), *cput1)
        return ess, eos

    cput1 = (logger.process_clock(), logger.perf_counter())

    emp2_ss = emp2_os = 0.
    for ind,oslice in enumerate(occslices):
        cderi = eris.init_eris(mp, oslice=oslice)
        for jnd,oslice2 in enumerate(occslices):
            if ind < jnd:
                continue

            if ind == jnd:
                ess, eos = _contract1occ(eris, cderi, oslice)
            else:
                cderi2 = eris.init_eris(mp, oslice=oslice2)
                ess, eos = _contract1occ(eris, cderi, oslice, cderi2, oslice2)
                ess_, eos_ = _contract1occ(eris, cderi2, oslice2, cderi, oslice)
                ess += ess_
                eos += eos_

            emp2_ss += ess
            emp2_os += eos
            cderi2 = None

            cput1 = log.timer('occblk [%d:%d,%d:%d]'%(*oslice,*oslice2), *cput1)
            log.debug1('Accum E_corr for occblk [%d:%d,%d:%d]  %.15g (SS)  %.15g (OS)  '
                       '%.15g', *oslice, *oslice2, emp2_ss/nkpts, emp2_os/nkpts,
                       (emp2_ss+emp2_os)/nkpts)
        cderi = None

    log.timer(mp.__class__.__name__, *cput0)

    emp2_ss /= nkpts
    emp2_os /= nkpts
    emp2 = emp2_ss + emp2_os

    return emp2, t2, emp2_ss, emp2_os

def _padding_k_idx(nmo, nocc, kind="split"):
    """A convention used for padding vectors, matrices and tensors in case when occupation numbers depend on the
    k-point index.
    Args:
        nmo (Iterable): k-dependent orbital number;
        nocc (Iterable): k-dependent occupation numbers;
        kind (str): either "split" (occupied and virtual spaces are split) or "joint" (occupied and virtual spaces are
        the joint;

    Returns:
        Two lists corresponding to the occupied and virtual spaces for kind="split". Each list contains integer arrays
        with indexes pointing to actual non-zero entries in the padded vector/matrix/tensor. If kind="joint", a single
        list of arrays is returned corresponding to the entire MO space.
    """
    if kind not in ("split", "joint"):
        raise ValueError("The 'kind' argument must be one of 'split', 'joint'")

    if kind == "split":
        indexes_o = []
        indexes_v = []
    else:
        indexes = []

    nocc = np.array(nocc)
    nmo = np.array(nmo)
    nvirt = nmo - nocc
    dense_o = np.amax(nocc)
    dense_v = np.amax(nvirt)
    dense_nmo = dense_o + dense_v

    for k_o, k_nmo in zip(nocc, nmo):
        k_v = k_nmo - k_o
        if kind == "split":
            indexes_o.append(np.arange(k_o))
            indexes_v.append(np.arange(dense_v - k_v, dense_v))
        else:
            indexes.append(np.concatenate((
                np.arange(k_o),
                np.arange(dense_nmo - k_v, dense_nmo),
            )))

    if kind == "split":
        return indexes_o, indexes_v

    else:
        return indexes


def padding_k_idx(mp, kind="split"):
    """A convention used for padding vectors, matrices and tensors in case when occupation numbers depend on the
    k-point index.

    This implementation stores k-dependent Fock and other matrix in dense arrays with additional dimensions
    corresponding to k-point indexes. In case when the occupation numbers depend on the k-point index (i.e. a metal) or
    when some k-points have more Bloch basis functions than others the corresponding data structure has to be padded
    with entries that are not used (fictitious occupied and virtual degrees of freedom). Current convention stores these
    states at the Fermi level as shown in the following example.

    +----+--------+--------+--------+
    |    |  k=0   |  k=1   |  k=2   |
    |    +--------+--------+--------+
    |    | nocc=2 | nocc=3 | nocc=2 |
    |    | nvir=4 | nvir=3 | nvir=3 |
    +====+========+========+========+
    | v3 |  k0v3  |  k1v2  |  k2v2  |
    +----+--------+--------+--------+
    | v2 |  k0v2  |  k1v1  |  k2v1  |
    +----+--------+--------+--------+
    | v1 |  k0v1  |  k1v0  |  k2v0  |
    +----+--------+--------+--------+
    | v0 |  k0v0  |        |        |
    +====+========+========+========+
    |          Fermi level          |
    +====+========+========+========+
    | o2 |        |  k1o2  |        |
    +----+--------+--------+--------+
    | o1 |  k0o1  |  k1o1  |  k2o1  |
    +----+--------+--------+--------+
    | o0 |  k0o0  |  k1o0  |  k2o0  |
    +----+--------+--------+--------+

    In the above example, `get_nmo(mp, per_kpoint=True) == (6, 6, 5)`, `get_nocc(mp, per_kpoint) == (2, 3, 2)`. The
    resulting dense `get_nmo(mp) == 7` and `get_nocc(mp) == 3` correspond to padded dimensions. This function will
    return the following indexes corresponding to the filled entries of the above table:

    >>> padding_k_idx(mp, kind="split")
    ([(0, 1), (0, 1, 2), (0, 1)], [(0, 1, 2, 3), (1, 2, 3), (1, 2, 3)])

    >>> padding_k_idx(mp, kind="joint")
    [(0, 1, 3, 4, 5, 6), (0, 1, 2, 4, 5, 6), (0, 1, 4, 5, 6)]

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        kind (str): either "split" (occupied and virtual spaces are split) or "joint" (occupied and virtual spaces are
        the joint;

    Returns:
        Two lists corresponding to the occupied and virtual spaces for kind="split". Each list contains integer arrays
        with indexes pointing to actual non-zero entries in the padded vector/matrix/tensor. If kind="joint", a single
        list of arrays is returned corresponding to the entire MO space.
    """
    return _padding_k_idx(mp.get_nmo(per_kpoint=True), mp.get_nocc(per_kpoint=True), kind=kind)


def padded_mo_energy(mp, mo_energy):
    """
    Pads energies of active MOs.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        mo_energy (ndarray): original non-padded molecular energies;

    Returns:
        Padded molecular energies.
    """
    frozen_mask = get_frozen_mask(mp)
    padding_convention = padding_k_idx(mp, kind="joint")
    nkpts = mp.nkpts

    result = np.zeros((nkpts, mp.nmo), dtype=mo_energy[0].dtype)
    for k in range(nkpts):
        result[np.ix_([k], padding_convention[k])] = mo_energy[k][frozen_mask[k]]

    return result


def padded_mo_coeff(mp, mo_coeff):
    """
    Pads coefficients of active MOs.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        mo_coeff (ndarray): original non-padded molecular coefficients;

    Returns:
        Padded molecular coefficients.
    """
    frozen_mask = get_frozen_mask(mp)
    padding_convention = padding_k_idx(mp, kind="joint")
    nkpts = mp.nkpts

    result = np.zeros((nkpts, mo_coeff[0].shape[0], mp.nmo), dtype=mo_coeff[0].dtype)
    for k in range(nkpts):
        result[np.ix_([k], np.arange(result.shape[1]), padding_convention[k])] = mo_coeff[k][:, frozen_mask[k]]

    return result


def _frozen_sanity_check(frozen, mo_occ, kpt_idx):
    '''Performs a few sanity checks on the frozen array and mo_occ.

    Specific tests include checking for duplicates within the frozen array.

    Args:
        frozen (array_like of int): The orbital indices that will be frozen.
        mo_occ (:obj:`ndarray` of int): The occupuation number for each orbital
            resulting from a mean-field-like calculation.
        kpt_idx (int): The k-point that `mo_occ` and `frozen` belong to.

    '''
    frozen = np.array(frozen)
    nocc = np.count_nonzero(mo_occ > 0)

    assert nocc, 'No occupied orbitals?\n\nnocc = %s\nmo_occ = %s' % (nocc, mo_occ)
    all_frozen_unique = (len(frozen) - len(np.unique(frozen))) == 0
    if not all_frozen_unique:
        raise RuntimeError('Frozen orbital list contains duplicates!\n\nkpt_idx %s\n'
                           'frozen %s' % (kpt_idx, frozen))
    if len(frozen) > 0 and np.max(frozen) > len(mo_occ) - 1:
        raise RuntimeError('Freezing orbital not in MO list!\n\nkpt_idx %s\n'
                           'frozen %s\nmax orbital idx %s' % (kpt_idx, frozen, len(mo_occ) - 1))


def get_nocc(mp, per_kpoint=False):
    '''Number of occupied orbitals for k-point calculations.

    Number of occupied orbitals for use in a calculation with k-points, taking into
    account frozen orbitals.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        per_kpoint (bool, optional): True returns the number of occupied
            orbitals at each k-point.  False gives the max of this list.

    Returns:
        nocc (int, list of int): Number of occupied orbitals. For return type, see description of arg
            `per_kpoint`.

    '''
    for i, moocc in enumerate(mp.mo_occ):
        if np.any(moocc % 1 != 0):
            raise RuntimeError("Fractional occupation numbers encountered @ kp={:d}: {}. This may have been caused by "
                               "smearing of occupation numbers in the mean-field calculation. If so, consider "
                               "executing mf.smearing_method = False; mf.mo_occ = mf.get_occ() prior to calling "
                               "this".format(i, moocc))
    if mp._nocc is not None:
        return mp._nocc
    elif mp.frozen is None:
        nocc = [np.count_nonzero(mp.mo_occ[ikpt]) for ikpt in range(mp.nkpts)]
    elif isinstance(mp.frozen, (int, np.integer)):
        nocc = [(np.count_nonzero(mp.mo_occ[ikpt]) - mp.frozen) for ikpt in range(mp.nkpts)]
    elif isinstance(mp.frozen[0], (int, np.integer)):
        [_frozen_sanity_check(mp.frozen, mp.mo_occ[ikpt], ikpt) for ikpt in range(mp.nkpts)]
        nocc = []
        for ikpt in range(mp.nkpts):
            max_occ_idx = np.max(np.where(mp.mo_occ[ikpt] > 0))
            frozen_nocc = np.sum(np.array(mp.frozen) <= max_occ_idx)
            nocc.append(np.count_nonzero(mp.mo_occ[ikpt]) - frozen_nocc)
    elif isinstance(mp.frozen[0], (list, np.ndarray)):
        nkpts = len(mp.frozen)
        if nkpts != mp.nkpts:
            raise RuntimeError('Frozen list has a different number of k-points (length) than passed in mean-field/'
                               'correlated calculation.  \n\nCalculation nkpts = %d, frozen list = %s '
                               '(length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        [_frozen_sanity_check(frozen, mo_occ, ikpt) for ikpt, frozen, mo_occ in zip(range(nkpts), mp.frozen, mp.mo_occ)]

        nocc = []
        for ikpt, frozen in enumerate(mp.frozen):
            max_occ_idx = np.max(np.where(mp.mo_occ[ikpt] > 0))
            frozen_nocc = np.sum(np.array(frozen) <= max_occ_idx)
            nocc.append(np.count_nonzero(mp.mo_occ[ikpt]) - frozen_nocc)
    else:
        raise NotImplementedError

    assert any(np.array(nocc) > 0), ('Must have occupied orbitals! \n\nnocc %s\nfrozen %s\nmo_occ %s' %
           (nocc, mp.frozen, mp.mo_occ))

    if not per_kpoint:
        nocc = np.amax(nocc)

    return nocc


def get_nmo(mp, per_kpoint=False):
    '''Number of orbitals for k-point calculations.

    Number of orbitals for use in a calculation with k-points, taking into account
    frozen orbitals.

    Note:
        If `per_kpoint` is False, then the number of orbitals here is equal to max(nocc) + max(nvir),
        where each max is done over all k-points.  Otherwise the number of orbitals is returned
        as a list of number of orbitals at each k-point.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.
        per_kpoint (bool, optional): True returns the number of orbitals at each k-point.
            For a description of False, see Note.

    Returns:
        nmo (int, list of int): Number of orbitals. For return type, see description of arg
            `per_kpoint`.

    '''
    if mp._nmo is not None:
        return mp._nmo

    if mp.frozen is None:
        nmo = [len(mp.mo_occ[ikpt]) for ikpt in range(mp.nkpts)]
    elif isinstance(mp.frozen, (int, np.integer)):
        nmo = [len(mp.mo_occ[ikpt]) - mp.frozen for ikpt in range(mp.nkpts)]
    elif isinstance(mp.frozen[0], (int, np.integer)):
        [_frozen_sanity_check(mp.frozen, mp.mo_occ[ikpt], ikpt) for ikpt in range(mp.nkpts)]
        nmo = [len(mp.mo_occ[ikpt]) - len(mp.frozen) for ikpt in range(mp.nkpts)]
    elif isinstance(mp.frozen, (list, np.ndarray)):
        nkpts = len(mp.frozen)
        if nkpts != mp.nkpts:
            raise RuntimeError('Frozen list has a different number of k-points (length) than passed in mean-field/'
                               'correlated calculation.  \n\nCalculation nkpts = %d, frozen list = %s '
                               '(length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        [_frozen_sanity_check(fro, mo_occ, ikpt) for ikpt, fro, mo_occ in zip(range(nkpts), mp.frozen, mp.mo_occ)]

        nmo = [len(mp.mo_occ[ikpt]) - len(mp.frozen[ikpt]) for ikpt in range(nkpts)]
    else:
        raise NotImplementedError

    assert all(np.array(nmo) > 0), ('Must have a positive number of orbitals!\n\nnmo %s\nfrozen %s\nmo_occ %s' %
           (nmo, mp.frozen, mp.mo_occ))

    if not per_kpoint:
        # Depending on whether there are more occupied bands, we want to make sure that
        # nmo has enough room for max(nocc) + max(nvir) number of orbitals for occupied
        # and virtual space
        nocc = mp.get_nocc(per_kpoint=True)
        nmo = np.max(nocc) + np.max(np.array(nmo) - np.array(nocc))

    return nmo


def get_frozen_mask(mp):
    '''Boolean mask for orbitals in k-point post-HF method.

    Creates a boolean mask to remove frozen orbitals and keep other orbitals for post-HF
    calculations.

    Args:
        mp (:class:`MP2`): An instantiation of an SCF or post-Hartree-Fock object.

    Returns:
        moidx (list of :obj:`ndarray` of `np.bool`): Boolean mask of orbitals to include.

    '''
    moidx = [np.ones(x.size, dtype=bool) for x in mp.mo_occ]
    if mp.frozen is None:
        pass
    elif isinstance(mp.frozen, (int, np.integer)):
        for idx in moidx:
            idx[:mp.frozen] = False
    elif isinstance(mp.frozen[0], (int, np.integer)):
        frozen = list(mp.frozen)
        for idx in moidx:
            idx[frozen] = False
    elif isinstance(mp.frozen[0], (list, np.ndarray)):
        nkpts = len(mp.frozen)
        if nkpts != mp.nkpts:
            raise RuntimeError('Frozen list has a different number of k-points (length) than passed in mean-field/'
                               'correlated calculation.  \n\nCalculation nkpts = %d, frozen list = %s '
                               '(length = %d)' % (mp.nkpts, mp.frozen, nkpts))
        [_frozen_sanity_check(fro, mo_occ, ikpt) for ikpt, fro, mo_occ in zip(range(nkpts), mp.frozen, mp.mo_occ)]
        for ikpt, kpt_occ in enumerate(moidx):
            kpt_occ[mp.frozen[ikpt]] = False
    else:
        raise NotImplementedError

    return moidx


def _add_padding(mp, mo_coeff, mo_energy):
    mo_coeff = _add_padding_mo_coeff(mp, mo_coeff)
    mo_energy = _add_padding_mo_energy(mp, mo_energy)
    return mo_coeff, mo_energy

def _add_padding_mo_coeff(mp, mo_coeff):
    if not np.all([x.shape[1] == mp.nmo for x in mo_coeff]):
        mo_coeff = padded_mo_coeff(mp, mo_coeff)
    return mo_coeff

def _add_padding_mo_energy(mp, mo_energy):
    if not np.all([x.shape[0] == mp.nmo for x in mo_energy]):
        mo_energy = padded_mo_energy(mp, mo_energy)
    return mo_energy


def make_rdm1(mp, t2=None, eris=None, kind="compact"):
    r"""
    Spin-traced one-particle density matrix in the MO basis representation.
    The occupied-virtual orbital response is not included.

    dm1[p,q] = <q_alpha^\dagger p_alpha> + <q_beta^\dagger p_beta>

    The convention of 1-pdm is based on McWeeney's book, Eq (5.4.20).
    The contraction between 1-particle Hamiltonian and rdm1 is
    E = einsum('pq,qp', h1, rdm1)

    Args:
        mp (KMP2): a KMP2 kernel object;
        t2 (ndarray): a t2 MP2 tensor;
        eris: generated by mp.ao2mo()
        kind (str): either 'compact' or 'padded' - defines behavior for k-dependent MO basis sizes;

    Returns:
        A k-dependent single-particle density matrix.
    """
    if kind not in ("compact", "padded"):
        raise ValueError("The 'kind' argument should be either 'compact' or 'padded'")
    d_imds = _gamma1_intermediates(mp, t2=t2, eris=eris)
    result = []
    padding_idxs = padding_k_idx(mp, kind="joint")
    for (oo, vv), idxs in zip(zip(*d_imds), padding_idxs):
        oo += np.eye(*oo.shape)
        d = block_diag(oo, vv)
        d += d.conj().T
        if kind == "padded":
            result.append(d)
        else:
            result.append(d[np.ix_(idxs, idxs)])
    return result


def make_rdm2(mp, t2=None, kind="compact"):
    r'''
    Spin-traced two-particle density matrix in MO basis

    .. math::

        dm2[p,q,r,s] = \sum_{\sigma,\tau} <p_\sigma^\dagger r_\tau^\dagger s_\tau q_\sigma>

    Note the contraction between ERIs (in Chemist's notation) and rdm2 is
    E = einsum('pqrs,pqrs', eri, rdm2)
    '''
    if kind not in ("compact", "padded"):
        raise ValueError("The 'kind' argument should be either 'compact' or 'padded'")
    if t2 is None: t2 = mp.t2
    dm1 = mp.make_rdm1(t2, "padded")
    nmo = mp.nmo
    nocc = mp.nocc
    nkpts = mp.nkpts
    dtype = t2.dtype

    dm2 = np.zeros((nkpts,nkpts,nkpts,nmo,nmo,nmo,nmo),dtype=dtype)
    for ki in range(nkpts):
        for kj in range(nkpts):
            for ka in range(nkpts):
                kb = mp.khelper.kconserv[ki, ka, kj]
                dovov = t2[ki, kj, ka].transpose(0,2,1,3) * 2 - t2[kj, ki, ka].transpose(1,2,0,3)
                dovov *= 2
                dm2[ki,ka,kj,:nocc,nocc:,:nocc,nocc:] = dovov
                dm2[ka,ki,kb,nocc:,:nocc,nocc:,:nocc] = dovov.transpose(1,0,3,2).conj()

    occidx = padding_k_idx(mp, kind="split")[0]
    for ki in range(nkpts):
        for i in occidx[ki]:
            dm1[ki][i,i] -= 2

    for ki in range(nkpts):
        for kp in range(nkpts):
            for i in occidx[ki]:
                dm2[ki,ki,kp,i,i,:,:] += dm1[kp].T * 2
                dm2[kp,kp,ki,:,:,i,i] += dm1[kp].T * 2
                dm2[kp,ki,ki,:,i,i,:] -= dm1[kp].T
                dm2[ki,kp,kp,i,:,:,i] -= dm1[kp]

    for ki in range(nkpts):
        for kj in range(nkpts):
            for i in occidx[ki]:
                for j in occidx[kj]:
                    dm2[ki,ki,kj,i,i,j,j] += 4
                    dm2[ki,kj,kj,i,j,j,i] -= 2

    if kind == "padded":
        return dm2
    else:
        idx = padding_k_idx(mp, kind="joint")
        result = []
        for kp in range(nkpts):
            for kq in range(nkpts):
                for kr in range(nkpts):
                    ks = mp.khelper.kconserv[kp, kq, kr]
                    result.append(dm2[kp,kq,kr][np.ix_(idx[kp],idx[kq],idx[kr],idx[ks])])
        return result


def _gamma1_intermediates(mp, t2=None, eris=None):
    nmo = mp.nmo
    nocc = mp.nocc
    nvir = nmo - nocc
    nkpts = mp.nkpts
    if t2 is None: t2 = mp.t2
    if t2 is None:
        if eris is None:
            eris = mp.ao2mo()
        mo_energy = eris.mo_energy
        mo_e_o = [mo_energy[k][:nocc] for k in range(nkpts)]
        mo_e_v = [mo_energy[k][nocc:] for k in range(nkpts)]
        nonzero_opadding, nonzero_vpadding = padding_k_idx(mp, kind="split")
        def get_eia(ki,ka):
            # Remove zero/padded elements from denominator
            eia = LARGE_DENOM * np.ones((nocc, nvir), dtype=mo_energy[0].dtype)
            n0_ovp_ia = np.ix_(nonzero_opadding[ki], nonzero_vpadding[ka])
            eia[n0_ovp_ia] = (mo_e_o[ki][:,None] - mo_e_v[ka])[n0_ovp_ia]
            return eia
        dtype = eris.dtype
    else:
        dtype = t2.dtype

    dm1occ = np.zeros((nkpts, nocc, nocc), dtype=dtype)
    dm1vir = np.zeros((nkpts, nvir, nvir), dtype=dtype)

    if t2 is None:
        mem_avail = mp.max_memory - lib.current_memory()[0]
        # 5 ovv-type tensors: gdi, gxi, ejab, t2di, t2xi
        # (Note that l2di and l2xi replace gdi and gxi and don't require more mem)
        blksize = int(np.floor(mem_avail*0.7 / (nocc*nvir**2.*5 * 16/1e6)))
        for ki in range(nkpts):
            for kj in range(nkpts):
                kblist = [mp.khelper.kconserv[ki,ka,kj] for ka in range(nkpts)]
                done = {(ka,kblist[ka]):False for ka in range(nkpts)}
                for ka in range(nkpts):
                    kb = kblist[ka]
                    if done[(ka,kb)] and done[(kb,ka)]:
                        continue

                    kijab = (ki,kj,ka,kb)
                    eia = get_eia(ki,ka)
                    ejb = get_eia(kj,kb)

                    cache_eris = not (mp.with_df_ints or mp.less_mem)
                    p1 = 0
                    for gdi,gxi in eris.loop_oovv(kijab, blksize=blksize,
                                                  cache_eris=cache_eris):
                        p0 = p1
                        p1 = p0 + gdi.shape[0]

                        ejab = lib.direct_sum('ia+jb->ijab', eia[p0:p1], ejb)
                        t2di = gdi.conj() / ejab
                        gdi = None
                        l2di = t2di.conj()

                        dm1vir[kb] += einsum('ijax,ijay->yx', l2di, t2di) * 2
                        dm1occ[kj] += einsum('ixab,iyab->xy', l2di, t2di) * 2

                        if gxi is None:
                            dm1vir[kb] -= einsum('ijax,ijya->yx', l2di, t2di)
                            dm1occ[kj] -= einsum('ixab,iyba->xy', l2di, t2di)
                        else:
                            t2xi = gxi.conj() / ejab.transpose(0,1,3,2)
                            gxi = None
                            l2xi = t2xi.conj()
                            dm1vir[ka] += einsum('ijax,ijay->yx', l2xi, t2xi) * 2
                            dm1occ[kj] += einsum('ixab,iyab->xy', l2xi, t2xi) * 2
                            dm1vir[kb] -= einsum('ijax,ijya->yx', l2di, t2xi)
                            dm1occ[kj] -= einsum('ixab,iyba->xy', l2di, t2xi)
                            dm1vir[ka] -= einsum('ijax,ijya->yx', l2xi, t2di)
                            dm1occ[kj] -= einsum('ixab,iyba->xy', l2xi, t2di)
                            t2xi = l2xi = None

                        ejab = t2di = l2di = None

                    done[(ka,kb)] = done[(kb,ka)] = True
    else:
        for ki in range(nkpts):
            for kj in range(nkpts):
                for ka in range(nkpts):
                    kb = mp.khelper.kconserv[ki, ka, kj]

                    dm1vir[kb] += (einsum('ijax,ijay->yx', t2[ki][kj][ka].conj(),
                                          t2[ki][kj][ka]) * 2 -
                                   einsum('ijax,ijya->yx', t2[ki][kj][ka].conj(),
                                          t2[ki][kj][kb]))
                    dm1occ[kj] += (einsum('ixab,iyab->xy', t2[ki][kj][ka].conj(),
                                          t2[ki][kj][ka]) * 2 -\
                                   einsum('ixab,iyba->xy', t2[ki][kj][ka].conj(),
                                          t2[ki][kj][kb]))
    return -dm1occ, dm1vir


class KMP2_direct(mp2.MP2):
    '''
    Attributes:
        less_mem (bool):
            This attr controls the algorithm for handling oovv-type ERIs
            if mf.with_df is FFTDF and is ignored otherwise. If set True,
            the 2*o^2*v^2 of memory for caching oovv-type ERIs is avoided,
            with the price of increasing CPU time. Default is False.
    '''

    def __init__(self, mf, frozen=None, mo_coeff=None, mo_occ=None):

        # >>>> sanity check
        if not hasattr(mf, 'with_df'):
            raise RuntimeError('mf must have with_df')
        if not isinstance(mf.with_df, df.RSDF):
            raise RuntimeError('mf.with_df must be RSDF object')
        if not hasattr(mf.with_df, 'direct'):
            raise RuntimeError('mf.with_df must have direct')
        if not mf.with_df.direct:
            raise RuntimeError('mf.with_df.direct must be True')
        # <<<<

        if mo_coeff is None: mo_coeff = mf.mo_coeff
        if mo_occ is None: mo_occ = mf.mo_occ

        self.mol = mf.mol
        self._scf = mf
        self.verbose = self.mol.verbose
        self.stdout = self.mol.stdout
        self.max_memory = mf.max_memory

        self.frozen = frozen
        if isinstance(self._scf.with_df, df.GDF):
            self.with_df_ints = True
        else:
            self.with_df_ints = False

        self.less_mem = False
        self.use_s2symm = True
        self._cderi = None
        self._cderi_to_save = tempfile.NamedTemporaryFile(dir=lib.param.TMPDIR)
        self.kilist = None
        self.incore_anyway = False

##################################################
# don't modify the following attributes, they are not input options
        self.kpts = mf.kpts
        self.mo_energy = mf.mo_energy
        self.nkpts = len(self.kpts)
        self.khelper = kpts_helper.KptsHelper(mf.cell, mf.kpts)
        self.mo_coeff = mo_coeff
        self.mo_occ = mo_occ
        self._nocc = None
        self._nmo = None
        self.e_corr = None
        self.e_corr_ss = None
        self.e_corr_os = None
        self.e_hf = None
        self.t2 = None
        self._keys = set(self.__dict__.keys())

    get_nocc = get_nocc
    get_nmo = get_nmo
    get_frozen_mask = get_frozen_mask
    make_rdm1 = make_rdm1
    make_rdm2 = make_rdm2

    def dump_flags(self):
        log = logger.new_logger(self)
        log.info("")
        log.info("******** %s ********", self.__class__)
        log.info("nkpts = %d", self.nkpts)
        log.info("nocc = %s", self.nocc)
        log.info("nmo = %s", self.nmo)
        log.info("with_df_ints = %s", self.with_df_ints)
        log.info("less_mem = %r", self.less_mem)
        log.info("use_s2symm = %r", self.use_s2symm)
        log.info("incore_anyway = %r", self.incore_anyway)
        log.info('kilist = %s', self.kilist)

        if self.frozen is not None:
            log.info("frozen orbitals = %s", self.frozen)
        log.info("max_memory %d MB (current use %d MB)",
                    self.max_memory, lib.current_memory()[0],
        )
        return self

    def kernel(self, mo_energy=None, mo_coeff=None, eris=None, with_t2=WITH_T2):
        if self.verbose >= logger.WARN:
            self.check_sanity()
        self.dump_flags()

        if mo_coeff is None: mo_coeff = self.mo_coeff

        if eris is None and not self.incore_anyway:
            eris = self.ao2mo(mo_coeff)

        self.e_hf = getattr(eris, 'e_hf', None)
        if self.e_hf is None:
            self.e_hf = self._scf.e_tot

        if self.use_s2symm:
            if self.incore_anyway:
                self.e_corr, self.t2, self.e_corr_ss, self.e_corr_os = \
                            kernel_s2_incore(self, mo_energy, mo_coeff, eris, with_t2)
            else:
                self.e_corr, self.t2, self.e_corr_ss, self.e_corr_os = \
                            kernel_s2(self, mo_energy, mo_coeff, eris, with_t2)
        else:
            self.e_corr, self.t2, self.e_corr_ss, self.e_corr_os = \
                        kernel(self, mo_energy, mo_coeff, eris, with_t2)

        self._finalize()

        return self.e_corr, self.t2

    def _finalize(self):
        '''Hook for dumping results and clearing up the object.'''
        logger.note(self, 'E(%s) = %.15g  E_corr = %.15g',
                    self.__class__.__name__, self.e_tot, self.e_corr)
        logger.info(self, 'E_corr(same-spin) = %.15g', self.e_corr_ss)
        logger.info(self, 'E_corr(oppo-spin) = %.15g', self.e_corr_os)
        return self

    def e_corr_scs(self, pss, pos):
        return self.e_corr_ss*pss + self.e_corr_os*pos
    def e_tot_scs(self, pss, pos):
        return self.e_tot-self.e_corr + self.e_corr_scs(pss,pos)
    def e_corr_sos(self, pos):
        return self.e_corr_scs(0., pos)
    def e_tot_sos(self, pos):
        return self.e_tot_scs(0., pos)

    def _memory_sanity_check(self, with_t2):
        nocc = self.nocc
        nvir = self.nmo - nocc
        nkpts = len(self.kpts)
        with_df_ints = self.with_df_ints

        mem_usage = 2*nocc*nvir**2 * 16/1e6 # ejab and t2i
        if not (with_df_ints or self.less_mem):
            mem_usage += 2*(nocc*nvir)**2 * 16/1e6 # (ia|jb) and (ib|ja)
        if with_t2:
            mem_usage += (nkpts**3 * (nocc * nvir)**2) * 16/1e6

        mem_avail = self.max_memory - lib.current_memory()[0]
        if mem_usage > mem_avail:
            logger.error(self, 'Insufficient memory! MP2 memory usage %.1f MB '
                         '(currently available %.1f MB)', mem_usage, mem_avail)
            raise MemoryError

    def ao2mo(self, mo_coeff=None):
        log = logger.new_logger(self)

        nocc = self.nocc
        nvir = self.nmo - nocc
        nkpts = len(self.kpts)
        with_df_ints = self.with_df_ints
        if mo_coeff is None: mo_coeff = self.mo_coeff

        mem_usage = 2*nocc*nvir**2 * 16/1e6 # ejab and t2i
        if with_df_ints:
            j3c_order = getattr(self, 'j3c_order', 'Lij')
            mydf = self._scf.with_df
            if mydf.auxcell is None:
                # Calculate naux based on precomputed GDF integrals
                naux = mydf.get_naoaux()
            else:
                naux = mydf.auxcell.nao_nr()
            mem_usage += (nkpts**2 * naux * nocc * nvir) * 16 / 1e6
            mem_avail = self.max_memory - lib.current_memory()[0]
            log.debug('mem Lov= %9.2f MB  mem avail= %9.2f MB', mem_usage, mem_avail)
            if mem_usage > mem_avail:
                log.info('Holding DF integrals outcore.')
                if isinstance(self._cderi, str):
                    restart = True
                    erifile = self._cderi
                else:
                    restart = False
                    if isinstance(self._cderi_to_save, str):
                        erifile = self._cderi_to_save
                    else:
                        erifile = self._cderi_to_save.name
                if restart:
                    log.info('Loading %s cderi from file: %s',
                             self.__class__.__name__, erifile)
                else:
                    log.info('Saving %s cderi to file: %s',
                             self.__class__.__name__, erifile)
                return _make_df_eris_outcore(self, mo_coeff, j3c_order,
                                             erifile=erifile, restart=restart)
            else:
                log.info('Holding DF integrals incore.')
                return _make_df_eris_incore(self, mo_coeff, j3c_order)
        else:
            return _make_eris_incore(self, mo_coeff)

    def ao2mo_incore(self, mo_coeff=None):
        assert(self.with_df_ints)
        if mo_coeff is None: mo_coeff = self.mo_coeff

        j3c_order = getattr(self, 'j3c_order', 'Lij')
        eris = _DFMP2ERIS_INCORE(j3c_order)
        eris = _MP2ERIS_INCORE._common_init_(eris, self, mo_coeff=mo_coeff)
        return eris

class _MP2ERIS_INCORE:

    def __init__(self):
        pass

    def _common_init_(self, mp, mo_coeff=None):
        from pyscf.pbc.lib.kpts_helper import gamma_point
        self.kpts = mp.kpts
        nkpts = len(self.kpts)
        self.dtype = np.double if gamma_point(self.kpts) else np.complex128
        self.dsize = 8 if gamma_point(self.kpts) else 16

        if mo_coeff is None:
            mo_coeff = mp.mo_coeff
        if mo_coeff is None:
            raise RuntimeError('mo_coeff, mo_energy are not initialized.\n'
                               'You may need to call mf.kernel() to generate them.')

        self.mo_coeff = _add_padding_mo_coeff(mp, mo_coeff)

        if mo_coeff is mp._scf.mo_coeff and mp._scf.converged:
            # The canonical MP2 from a converged SCF result. Rebuilding fock
            # and e_hf can be skipped
            self.mo_energy = _add_padding_mo_energy(mp, mp._scf.mo_energy)
            self.fock = [np.diag(self.mo_energy[k]) for k in range(nkpts)]
            self.e_hf = mp._scf.e_tot
        else:
            dm = mp._scf.make_rdm1(mo_coeff, mp.mo_occ)
            vhf = mp._scf.get_veff(mp.mol, dm)
            fockao = mp._scf.get_fock(vhf=vhf, dm=dm)
            self.fock = [np.linalg.multi_dot(self.mo_coeff[k].conj().T, fockao[k],
                                             self.mo_coeff[k])
                         for k in range(nkpts)]
            self.e_hf = mp._scf.energy_tot(dm=dm, vhf=vhf)
            self.mo_energy = [self.fock[k].diagonal().real for k in range(nkpts)]

        self.nocc = mp.nocc
        self.nmo = mp.nmo
        self._fao2mo = mp._scf.with_df.ao2mo

        return self

    def fao2mo(self, mo_iajb, kpts_iajb):
        shape = tuple([mo.shape[1] for mo in mo_iajb])
        fac = 1./len(self.kpts)
        _fao2mo = self._fao2mo
        return _fao2mo(mo_iajb, kpts_iajb, compact=False
                       ).reshape(*shape).transpose(0,2,1,3) * fac

    def get_oovv(self, kijab, shls_slice_i=None):
        ki,kj,ka,kb = kijab
        kpts = self.kpts
        mo_coeff = self.mo_coeff
        nocc = self.nocc
        if shls_slice_i is None:
            shls_slice_i = (0, nocc)

        orbo_i = mo_coeff[ki][:,shls_slice_i[0]:shls_slice_i[1]]
        orbo_j = mo_coeff[kj][:,:nocc]
        orbv_a = mo_coeff[ka][:,nocc:]
        orbv_b = mo_coeff[kb][:,nocc:]
        return self.fao2mo((orbo_i,orbv_a,orbo_j,orbv_b),
                           (kpts[ki],kpts[ka],kpts[kj],kpts[kb]))

    def loop_oovv(self, kijab, swap_kakb=True, cache_eris=False, max_memory=2000,
                  blksize=None):
        r''' Given kijab = (ki,kj,ka,kb) the indices of four kpts in self.kpts,
        this function returns blocks of the oovv tensor (slicing the first [o]
        index) for kijab = (ki,kj,ka,kb) and (if swap_ab=True) kijba = (ki,kj,kb,ka).

        Args:
            kijab (tuple):
                kijab = (ki,kj,ka,kb)
            swap_kakb (bool):
                If True and ka != kb, both direct term 'gdi' (ki,kj,ka,kb) and the
                (ka,kb)-exchange term 'gxi' (ki,kj,kb,ka) will be returned.
                Otherwise, the returned 'gxi' is None. The default is True.
            cache_eris (bool):
                If True, the full oovv tensor will be cached. Otherwise, the
                corresponding block of oovv tensor is computed on the fly.
            max_memory (float):
                If blksize is not given, use this to determine an appropriate blksize.
            blksize (int):
                The block size over which the first [o] index is looped.

        Returns:
            gdi, gxi:
                The direct and (ka,kb)-exchange terms of oovv, where gxi is None if
                swap_kakb is False or ka == kb.
        '''
        ki,kj,ka,kb = kijab
        kijba = (ki,kj,kb,ka)
        swap_kakb &= ka != kb
        nocc = self.nocc
        nvir = self.nmo - nocc

        if cache_eris:
            # caching ijab and ijba
            oovv_ijab = self.get_oovv(kijab)
            oovv_ijba = self.get_oovv(kijba) if swap_kakb else oovv_ijab
            def get_oovv(shls_slice, kind):
                p0,p1 = shls_slice
                if kind == 'd':
                    return oovv_ijab[p0:p1]
                else:
                    return oovv_ijba[p0:p1]
        else:
            def get_oovv(shls_slice, kind):
                if kind == 'd':
                    return self.get_oovv(kijab, shls_slice_i=shls_slice)
                else:
                    return self.get_oovv(kijba, shls_slice_i=shls_slice)

        if blksize is None:
            mem_avail = max_memory - lib.current_memory()[0]
            fac = 2 if swap_kakb else 1
            blksize = int(np.floor(mem_avail * 0.7 / (nocc*nvir**2*fac * 16/1e6)))

        for p0,p1 in lib.prange(0, self.nocc, blksize):
            shls_slice = (p0,p1)
            gdi = get_oovv(shls_slice, 'd')
            gxi = get_oovv(shls_slice, 'x') if swap_kakb else None
            yield gdi, gxi
            gdi = gxi = None

        if cache_eris:
            oovv_ijab = oovvijba = None

class _DFMP2ERIS_INCORE(_MP2ERIS_INCORE):

    def __init__(self, j3c_order='Lij'):
        self.j3c_order = j3c_order

    def _common_init_(self, mp, mo_coeff=None):
        _MP2ERIS_INCORE._common_init_(self, mp, mo_coeff=mo_coeff)
        self.cderi = self.init_eris(mp)
        return self

    def init_eris(self, mp, oslice=None):
        return _init_mp_df_eris(mp, mo_coeff=self.mo_coeff, j3c_order=self.j3c_order,
                                oslice=oslice)

    def get_cderi(self, ki, ka, shls_slice_i=None):
        if shls_slice_i is None:
            return self.cderi[ki,ka]
        else:
            if self.j3c_order == 'Lij':
                return self.cderi[ki,ka][:,shls_slice_i[0]:shls_slice_i[1]]
            else:
                return self.cderi[ki,ka][shls_slice_i[0]:shls_slice_i[1],:]

    def get_oovv(self, kijab, shls_slice_i=None):
        ki,kj,ka,kb = kijab
        nkpts = len(self.kpts)
        if self.j3c_order == 'Lij':
            return einsum("Lia,Ljb->iajb", self.get_cderi(ki,ka,shls_slice_i),
                          self.get_cderi(kj,kb)).transpose(0,2,1,3) / nkpts
        else:
            return einsum("iaL,jbL->iajb", self.get_cderi(ki,ka,shls_slice_i),
                          self.get_cderi(kj,kb)).transpose(0,2,1,3) / nkpts

class _DFMP2ERIS_OUTCORE(_DFMP2ERIS_INCORE):

    def _common_init_(self, mp, mo_coeff=None, erifile=None, dataname='Lov',
                      restart=False):
        _MP2ERIS_INCORE._common_init_(self, mp, mo_coeff=mo_coeff)
        nocc = self.nocc
        nvir = self.nmo - nocc
        nkpts = len(self.kpts)
        mydf = mp._scf.with_df
        if mydf.auxcell is None:
            # Calculate naux based on precomputed GDF integrals
            naux = mydf.get_naoaux()
        else:
            naux = mydf.auxcell.nao_nr()
        if erifile is None: erifile = self._cderi_to_save
        if restart:
            self.feri = h5py.File(erifile, 'r')
            self.cderi = self.feri[dataname]
        else:
            self.feri = h5py.File(erifile, 'w')
            self.cderi = self.feri.create_group(dataname)
            _init_mp_df_eris(mp, mo_coeff=self.mo_coeff, Lov=self.cderi,
                             j3c_order=self.j3c_order)
        return self

    def get_cderi(self, ki, ka, shls_slice_i=None):
        key = '%d,%d'%(ki,ka)
        if shls_slice_i is None:
            return self.cderi[key]
        else:
            if self.j3c_order == 'Lij':
                return self.cderi[key][:,shls_slice_i[0]:shls_slice_i[1]]
            else:
                return self.cderi[key][shls_slice_i[0]:shls_slice_i[1],:]

def _make_eris_incore(mp, mo_coeff=None):
    eris = _MP2ERIS_INCORE()._common_init_(mp, mo_coeff=mo_coeff)
    return eris

def _make_df_eris_incore(mp, mo_coeff=None, j3c_order='Lij'):
    return _DFMP2ERIS_INCORE(j3c_order)._common_init_(mp, mo_coeff=mo_coeff)

def _make_df_eris_outcore(mp, mo_coeff=None, j3c_order='Lij', erifile=None,
                          restart=False):
    return _DFMP2ERIS_OUTCORE(j3c_order)._common_init_(mp, mo_coeff=mo_coeff,
                                                       erifile=erifile, dataname='Lov',
                                                       restart=restart)

def ao2mo_df(cderi, mo_coeff, nocc, kpts, Lov=None):
    from pyscf.pbc.df import df
    from pyscf.ao2mo import _ao2mo
    from pyscf.pbc.lib.kpts_helper import gamma_point

    nkpts = len(kpts)
    nao, nmo = mo_coeff[0].shape
    nvir = nmo - nocc
    if gamma_point(kpts):
        dtype = np.double
    else:
        dtype = np.complex128
    dtype = np.result_type(dtype, *mo_coeff)

    if Lov is None:
        Lov = np.empty((nkpts, nkpts), dtype=object)
    elif isinstance(Lov, np.ndarray):
        assert(Lov.dtype == object)
    elif not isinstance(Lov, h5py.Group):
        raise TypeError('Input Lov must be np.ndarray or h5py.Group.')

    bra_start = 0
    bra_end = nocc
    ket_start = nmo+nocc
    ket_end = ket_start + nvir
    with h5py.File(cderi, 'r') as f:
        kptij_lst = f['j3c-kptij'][:]
        tao = []
        ao_loc = None
        for ki, kpti in enumerate(kpts):
            for kj, kptj in enumerate(kpts):
                kpti_kptj = np.array((kpti, kptj))
                Lpq_ao = np.asarray(df._getitem(f, 'j3c', kpti_kptj, kptij_lst))

                mo = np.hstack((mo_coeff[ki], mo_coeff[kj]))
                mo = np.asarray(mo, dtype=dtype, order='F')
                if dtype == np.double:
                    out = _ao2mo.nr_e2(Lpq_ao, mo, (bra_start, bra_end, ket_start, ket_end), aosym='s2')
                else:
                    #Note: Lpq.shape[0] != naux if linear dependency is found in auxbasis
                    if Lpq_ao[0].size != nao**2:  # aosym = 's2'
                        Lpq_ao = lib.unpack_tril(Lpq_ao).astype(np.complex128)
                    out = _ao2mo.r_e2(Lpq_ao, mo, (bra_start, bra_end, ket_start, ket_end), tao, ao_loc)
                if isinstance(Lov, np.ndarray):
                    Lov[ki, kj] = out.reshape(-1, nocc, nvir)
                else:
                    Lov['%d,%d'%(ki,kj)] = out.reshape(-1, nocc, nvir)

    return Lov

def _init_mp_df_eris(mp, mo_coeff=None, Lov=None, j3c_order='Lij', oslice=None):
    """Compute 3-center electron repulsion integrals, i.e. (L|ov),
    where `L` denotes DF auxiliary basis functions and `o` and `v` occupied and virtual
    canonical crystalline orbitals. Note that `o` and `v` contain kpt indices `ko` and `kv`,
    and the third kpt index `kL` is determined by the conservation of momentum.

    Arguments:
        mp (KMP2) -- A KMP2 instance
        mo_coeff (list) -- MO coeff by kpts. Generated from _add_padding if None.
        Lov (ndarray or H5 group) -- where to store integrals. If None, a numpy
            ndarray is created.

    Returns:
        Lov (np.ndarray or H5 group) -- 3-center DF ints, with shape
            (nkpts, nkpts, naux, nocc, nvir)
    """
    log = logger.new_logger(mp)

    nocc = mp.nocc
    if mo_coeff is None: mo_coeff = _add_padding_mo_coeff(mp, mp.mo_coef)
    kpts = mp.kpts

    # adjust mo and nocc if only certain occ slice is requested
    if oslice is not None:
        i0, i1 = oslice
        mo_coeff = [np.hstack((x[:,i0:i1],x[:,nocc:])) for x in mo_coeff]
        nocc = i1 - i0

    mydf = mp._scf.with_df

    cput0 = (logger.process_clock(), logger.perf_counter())
    if getattr(mydf, 'direct', False):
        kernel_ao2mo = getattr(mp, 'kernel_ao2mo', 1)
        from pyscf.pbc.df.rsdf_direct_ao2mo import ao2mo_e2
        mo_coeff1 = [mo[:,:nocc] for mo in mo_coeff]
        mo_coeff2 = [mo[:,nocc:] for mo in mo_coeff]
        mo_coeffs = (mo_coeff1, mo_coeff2)
        Lov = ao2mo_e2(mydf, mo_coeffs, kpts, j3c_order=j3c_order, kernel=kernel_ao2mo,
                       out=Lov)
    else:
        if mydf._cderi is None:
            mydf.build()
        cderi = mydf._cderi
        Lov = ao2mo_df(cderi, mo_coeff, nocc, kpts, Lov=Lov)
    log.timer("transforming DF-MP2 integrals", *cput0)

    return Lov


KRMP2_direct = KMP2_direct


# from pyscf.pbc import scf
# scf.khf.KRHF.MP2 = lib.class_as_method(KRMP2)
# scf.kghf.KGHF.MP2 = None
# scf.krohf.KROHF.MP2 = None


if __name__ == '__main__':
    # from pyscf.pbc import gto, scf
    #
    # cell = gto.Cell()
    # cell.atom='''
    # He 0 0 0
    # He 1 0 0
    # '''
    # cell.basis = 'gth-dzvp'
    # cell.pseudo = 'gth-pade'
    # cell.a = np.eye(3) * 3
    # cell.mesh = [35,35,35]  # small PW mesh to save cost
    # cell.build()
    # cell.verbose = 7
    #
    # # Running HF and MP2 with 1x1x2 Monkhorst-Pack k-point mesh
    # # kmf = scf.KRHF(cell, kpts=cell.make_kpts([1,1,2]), exxdiv=None)
    # kmf = scf.KRHF(cell, kpts=cell.make_kpts([1,1,2]), exxdiv=None).rs_density_fit()
    # kmf.chkfile = 'mf.chk'
    # ehf = kmf.kernel()
    # #
    # # kmf.with_df.direct = True
    # # mymp = KMP2(kmf)
    # # mymp.j3c_order = 'ijL'
    # # mymp.kernel_ao2mo = 2
    # # emp2, t2 = mymp.kernel()
    # # print(emp2 - -0.0507276327223342)
    # #
    # # mymp.t2 = None
    # # dm1_with_t2 = mymp.make_rdm1(t2=t2)
    # # dm1_without_t2 = mymp.make_rdm1(t2=None)
    # # nkpts = len(kmf.kpts)
    # # dm1_err = max([abs(dm1_with_t2[k]-dm1_without_t2[k]).max() for k in range(nkpts)])
    # # print(dm1_err)

    import sys
    from pyscf.lib import logger
    log = logger.Logger(sys.stdout, 6)

    try:
        fchk = sys.argv[1]
        j3c_order = sys.argv[2]
        kernel_ao2mo = int(sys.argv[3])
        omega = float(sys.argv[4])
        mem = float(sys.argv[5]) * 950
    except:
        log.warn('Usage: fchk, j3c_order, kernel_ao2mo, omega, mem')
        sys.exit(1)

    from pyscf.pbc.scf.chkfile import load_scf
    cell, scf_res = load_scf(fchk)
    cell.max_memory = mem
    kpts = scf_res['kpts']
    mo_coeff = scf_res['mo_coeff']
    mo_occ = scf_res['mo_occ']
    mo_energy = scf_res['mo_energy']
    e_tot = scf_res['e_tot']

    # auxbasis
    auxbasname = 'cc-pvdz-jkfit'
    atms = np.unique([cell.atom_symbol(iatm) for iatm in range(cell.natm)])
    from pyscf import gto as molgto
    auxbasis = {atm:molgto.M(atom=atm, basis=auxbasname, spin=None)._basis[atm] for atm in atms}
    print(auxbasis)
    sys.exit(1)

    from zflow.pyscf_helper import guess_frozen
    frozen = guess_frozen(cell)
    log.warn('Using frozen= %d', frozen)

    from pyscf.pbc import scf
    mf = scf.KRHF(cell, kpts).rs_density_fit()
    mf.with_df.direct = True
    mf.with_df.omega = omega
    mf.with_df.use_bvk = [True, False]
    mf.with_df.build()
    mf.mo_coeff = mo_coeff
    mf.mo_energy = mo_energy
    mf.mo_occ = mo_occ
    mf.e_tot = e_tot
    mf.converged = True

    mmp = KMP2_direct(mf, frozen=frozen)
    mmp.j3c_order = j3c_order
    mmp.kernel_ao2mo = kernel_ao2mo
    mmp.kernel()
